### ISSUE TITLE
Adjust highlighting for color blindness

### ISSUE THREAD

**Issue by ersimont** [ersimont/sudoku-support#17]
Some of the colors/highlights in the strategy explanations that try to visualize them on the board - they are not friendly for different types of vision deficiencies.

**Comment by ersimont** [comment]
Done

**Comment by shfislrh** [comment]
While I applaud this change, shouldn't it have been done as a separate theme rather than in the default settings (or just a toggle) as your once beautiful colour scheme is now really quite garish.  I like change and progress, but I feel you should have the choice to apply it or not.

**Comment by ersimont** [comment]
Thank you for the feedback. The phrase "once beautiful color scheme" is motivating. I'll open a separate ticket to track this.

I am currently in the middle of a big rewrite of the way the board is rendered to address performance on phones. It should not have much visual impact, but it may give me an easier way to make a toggle that restores the app's former beauty 🙂.
