### ISSUE TITLE
Sizing issue

### ISSUE THREAD

**Issue by shfislrh** [ersimont/sudoku-support#26]
From today the sizing seems to have changed, with no way to revert to how it was.  Suspect it's fine on a mobile but on a tablet (galaxy tab s6) all the numbers are huge.

Can zoom in (worse) but can't zoom out.

Landscape mode now only shows half the board, totally unplayable

Please give the option to resize (it used to be perfect), my absolute favourite app is now very difficult to play.

**Comment by ersimont** [comment]
Ohhh landscape is indeed broken! Very sorry, and thank you for submitting the issue. I may be able to look into this later today.

**Comment by shfislrh** [comment]
Hi Eric

Thanks for this.  I'm more worried about the large numbers than landscape problem tbh.  I love this app but the sizing makes it too "in your face" to use

Ps you should sell it, imho the best soduko app out there !

Regards
Lee


________________________________

**Comment by ersimont** [comment]
No, wait. I am having trouble reproducing. Here is a screenshot of the app from my tablet (Galaxy Tab A7), in landscape mode. More investigation is underway. Let me know if you have any more info that can help, like if it is always unplayably big, or only after a certain sequence of events.

![image](https://user-images.githubusercontent.com/8042088/168478083-914e7d90-4385-4e85-9f9f-857a2f0e2d84.png)

**Comment by ersimont** [comment]
Ahh sorry I just saw your last message. So it's not just the "only half the board" issue, it's just a preference to not have it get so big. OK let me think on that a little more and get back to you.

I made it expand to be bigger so it's nicer when I'm making [YouTube videos](https://youtu.be/c_hI3n0_hvg) :). As a temporary workaround is your tablet able to display 2 apps side-by-side? If you are able to somehow reduce the amount of screen space the app takes up, the size of the board should update accordingly.

I know that's not a good solution. But maybe something temporary while I think of how to nicely let you set your own size.

**Comment by shfislrh** [comment]
You didn't attach screenshot but I guess it's working ok for you 🙂

On tab S6 (maybe higher resolution than the lite ??) I don't need to do anything to "break" landscape, it's always only showing half a screen (attached screenshot).  Putting it in split screen mode (still landscape) shows it perfectly though (which is what I may have to revert to so I can get my daily soduko requirement 😀).  I did reset tablet etc just to check tablet wasn't just "having a moment".  I can pinch to zoom in, but cannot pinch to zoom out any more than screenshot shows

Yeah my issue is that the "board" now fills the screen, and it's like "woah" in your face.  Only started happening last 24 hours or so, previous to that it's was great.  God only knows what it would be like on the tab ultra (15 inch)

Not sure what else I can show tbh.  If you do need any more info or me to test anything then just let me know

Regards
Lee



________________________________

**Comment by ersimont** [comment]
Would you test this out before I make it live? https://simonton-sudoku--staging-uungnbfp.web.app

There is a new setting to set a custom board size.

**Comment by shfislrh** [comment]
But unsure tbh.  I set to anything below 300 and it defaults back to full screen.  Set to 300 and it goes small. Set to 500 and it looks spot on. Weirdly if I leave to "auto" it goes to the size I like, but as soon as you come out of settings it reverts to full screen again.

Video attached should explain better
https://drive.google.com/file/d/1XMpKR6IQtr0XjRpWNBPZ88HcJwDl35Bs/view?usp=drivesdk


Regards
Lee
________________________________

**Comment by ersimont** [comment]
Thank you for the video. It's helpful to see you struggle with my lacking design 🙂. I added a simple message to indicate that 300 is the minimum size (it gets messed up if you try to go lower, and the toolbars are 300px wide anyway). If you check the same link again - do you think that's enough to make it intuitive? (You may have to open it, wait 10 seconds while it updates in the background, then re-open it again to see the changes.)

I was confused why the board size kept getting smaller and bigger for you when you opened & closed the settings. Finally I figured it out: it adjusts for when the keyboard is open! That makes the playable space smaller, so the board shrinks to accommodate. I'll look into whether I can do anything about that. It's weird.

**Comment by shfislrh** [comment]
Yep that msg is fine.  Suspect people who use the app are logical people anyway so only need a hint as to what to try

Can see why you "full screened" the app by default btw, looks great on my galaxy s10 🙂. Now with sizing ability it will be great on my tablet too

Many thanks
Lee


________________________________

**Comment by ersimont** [comment]
Excellent. Thank you again for raising the issue, and also for your help making the fix for it better. I'm deploying this to the real app now. Next time you open it should update, and the time after that you should have the new setting available!
