### ISSUE TITLE
Toggle high contrast

### ISSUE THREAD

**Issue by ersimont** [ersimont/sudoku-support#30]
Provide a way to toggle in/out of the high contrast colors from #17.

**Comment by ersimont** [comment]
@shfislrh would you mind checking this feature out here?: https://simonton-sudoku--staging-a33s8y0l.web.app/

I think all the colors should be exactly back to where they were, and there is a new "high contrast" theme in the settings.

**Comment by shfislrh** [comment]
Hi Eric

I can't get to my "main" screen (galaxy tab s6) but on my phone (much smaller s21) it all looks good.  😀

Regards
Lee
________________________________

**Comment by ersimont** [comment]
OK great, thanks! I assume the colors will look about the same on your main screen, so I'll move ahead with it like this.

**Comment by ersimont** [comment]
This is now live. Thanks for the feedback that prompted it!
