### ISSUE TITLE
No longer works on IPhone 

### ISSUE THREAD

**Issue by zach6585** [ersimont/sudoku-support#51]
As of a few months ago, the game is no longer working in browsers on IPhone. Most things do work, but you can’t actually click in the boxes.

**Comment by ersimont** [comment]
I realize it has taken me approximately forever to respond. Very sorry about that.

I am on the case. Thank you for bringing this to my attention. I don't have an iOS device, so I would never have found out!

**Comment by zach6585** [comment]
If you want, I can send photos/videos displaying the problem since I do have an iOS device.

**Comment by ersimont** [comment]
I appreciate the offer. I have a lead. I'll let you know if it doesn't pan out!

**Comment by ersimont** [comment]
I think I have it solved. If you'd like to check it out, another set of eyes seeing if there any problem remaining would be great! You can try it here: https://simonton-sudoku--staging-r1tgi3qr.web.app

**Comment by zach6585** [comment]
Yes it works perfectly!

**Comment by ersimont** [comment]
OK great, thank you again for the report, and thank you for verifying it. I'm deploying it now.

Note that next time you open the app it will download the update in the background, and then the next time after that you will see the changes.
